title: Blog
description: >- 

domain: riolu.com
baseurl: "/blog/"
url: "https://riolu.com" 

author:
  name: lucario
  email: "10692069+lucario@users.noreply.github.com"
  
minima:
  skin: auto

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
