title: Blog
description: >- 

# author:
#   name: lucario
#   email: "10692069+lucario@users.noreply.github.com"
  
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/lucario" }

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
